## nimoutline: one-line types and routine signatures for a whole file.
##
## Reads a Nim file and prints every type definition and routine signature with
## its line number — the fast way to see a file's shape without reading it.
##
## Uses the shared walkers in shared/ast_utils, so it agrees with `extract` and
## `inspect` about which routines exist. It previously carried its own copies of
## the render helpers and its own traversal, which had drifted: the copies were
## missing nkVarTy handling and had unguarded n[1]/n[2] indexing, and the walker
## stopped at every routine so nested procs were invisible.

import compiler/[ast]
import std/[strutils, parseopt, os]
import shared/[compiler_env, ast_utils]

type
  OutlineItem = object
    line: int
    content: string

proc main() =
  var p = initOptParser()
  var inputFile = ""
  var outputFile = ""
  var helpRequested = false

  while true:
    p.next()
    case p.kind
    of cmdEnd: break
    of cmdShortOption, cmdLongOption:
      case p.key
      of "h", "help":
        helpRequested = true
      of "o", "out":
        outputFile = p.val
      else:
        stderr.writeLine "Error: Unknown option: " & p.key
        quit(1)
    of cmdArgument:
      if inputFile == "":
        inputFile = p.key
      elif outputFile == "":
        outputFile = p.key
      else:
        stderr.writeLine "Error: Unexpected argument: " & p.key
        quit(1)

  if helpRequested or inputFile == "":
    echo """
nimoutline - Nim source code summary generator

Usage:
  nimoutline <input_file.nim> [options]

Options:
  -o, --out:<file>   Write to a file instead of stdout.
  -h, --help         Show this help message.
"""
    quit(0)

  if not fileExists(inputFile):
    stderr.writeLine "Error: File does not exist: " & inputFile
    quit(1)

  let parsed = parseNimFile(inputFile)
  if parsed.ast == nil or parsed.errors.len > 0:
    stderr.writeLine "Error: Syntax errors in " & inputFile & ":"
    for err in parsed.errors:
      stderr.writeLine "  " & err
    quit(1)

  var
    types: seq[OutlineItem] = @[]
    routines: seq[OutlineItem] = @[]

  # Shared walkers: these recurse unconditionally, so routines nested inside
  # other routines appear here exactly as they do in `extract` and `inspect`.
  for n in collectTypeDefs(parsed.ast):
    types.add OutlineItem(line: n.info.line.int, content: renderTypeDefConcise(n))
  for n in collectRoutines(parsed.ast):
    routines.add OutlineItem(line: n.info.line.int, content: renderRoutineSignature(n))

  # Generate outline text
  var outputLines: seq[string] = @[]
  outputLines.add "Outline of " & inputFile
  outputLines.add "Generated by nimoutline"
  outputLines.add ""
  outputLines.add "================================================================================"
  outputLines.add "TYPES"
  outputLines.add "================================================================================"
  if types.len == 0:
    outputLines.add "(no types defined)"
  else:
    for t in types:
      outputLines.add "Line " & align($t.line, 4) & ": " & t.content

  outputLines.add ""
  outputLines.add "================================================================================"
  outputLines.add "ROUTINES"
  outputLines.add "================================================================================"
  if routines.len == 0:
    outputLines.add "(no routines defined)"
  else:
    for r in routines:
      outputLines.add "Line " & align($r.line, 4) & ": " & r.content

  let outputText = outputLines.join("\n") & "\n"

  # stdout by default: the caller is usually a pipe or an agent, and writing a
  # sidecar file it never asked for both litters the tree and forces a second
  # read to get at the result. `-o` opts back into a file.
  if outputFile == "":
    stdout.write outputText
  else:
    try:
      writeFile(outputFile, outputText)
      echo "Outline successfully written to: ", outputFile
    except CatchableError as e:
      stderr.writeLine "Error: Could not write outline to: " & outputFile & " (" & e.msg & ")"
      quit(1)

when isMainModule:
  main()
